from openvisionstudio.engine.graph_model import GraphModel


def export_pipeline_to_python(graph: GraphModel) -> str:
    lines = [
        '"""Generated by OpenVisionStudio."""',
        "import argparse",
        "import cv2",
        "",
        "def main() -> None:",
        "    parser = argparse.ArgumentParser()",
        "    parser.add_argument('--input', required=False)",
        "    parser.add_argument('--output', required=False)",
        "    args = parser.parse_args()",
        "    image = cv2.imread(args.input) if args.input else None",
        "    # TODO: expand generated graph logic",
        "    if image is not None and args.output:",
        "        cv2.imwrite(args.output, image)",
        "",
        "if __name__ == '__main__':",
        "    main()",
    ]
    return "\n".join(lines)
